language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli karma forever bower --production --loglevel warn
  - bower install --production --quiet
  - forever start karma-server.js
after_script:
  - forever stop karma-server.js
